// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// assign2visium_spots
Rcpp::List assign2visium_spots(const arma::mat& mole_coords, const arma::umat& array_coords, const arma::mat& img_coords, const double spot_radius);
RcppExport SEXP _BinXenium_assign2visium_spots(SEXP mole_coordsSEXP, SEXP array_coordsSEXP, SEXP img_coordsSEXP, SEXP spot_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mole_coords(mole_coordsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type array_coords(array_coordsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type img_coords(img_coordsSEXP);
    Rcpp::traits::input_parameter< const double >::type spot_radius(spot_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(assign2visium_spots(mole_coords, array_coords, img_coords, spot_radius));
    return rcpp_result_gen;
END_RCPP
}
// assign2visium_subspots
Rcpp::List assign2visium_subspots(const arma::mat& mole_coords, const Rcpp::CharacterVector& mole_assigned_barcodes, const arma::umat& subspot_ids, const arma::mat& img_subspot_coords, const Rcpp::CharacterVector& subspot_assigned_barcodes, const arma::mat& img_spot_coords, const Rcpp::CharacterVector& spot_barcodes, const double spot_radius);
RcppExport SEXP _BinXenium_assign2visium_subspots(SEXP mole_coordsSEXP, SEXP mole_assigned_barcodesSEXP, SEXP subspot_idsSEXP, SEXP img_subspot_coordsSEXP, SEXP subspot_assigned_barcodesSEXP, SEXP img_spot_coordsSEXP, SEXP spot_barcodesSEXP, SEXP spot_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mole_coords(mole_coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type mole_assigned_barcodes(mole_assigned_barcodesSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type subspot_ids(subspot_idsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type img_subspot_coords(img_subspot_coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type subspot_assigned_barcodes(subspot_assigned_barcodesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type img_spot_coords(img_spot_coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type spot_barcodes(spot_barcodesSEXP);
    Rcpp::traits::input_parameter< const double >::type spot_radius(spot_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(assign2visium_subspots(mole_coords, mole_assigned_barcodes, subspot_ids, img_subspot_coords, subspot_assigned_barcodes, img_spot_coords, spot_barcodes, spot_radius));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BinXenium_assign2visium_spots", (DL_FUNC) &_BinXenium_assign2visium_spots, 4},
    {"_BinXenium_assign2visium_subspots", (DL_FUNC) &_BinXenium_assign2visium_subspots, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_BinXenium(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
